### ISSUE TITLE
implement -params.yml file

### ISSUE THREAD

**Issue by andreashandel** [metrumresearchgroup/bbr.bayes#12]
sometime soonish, we should implement Jonathan's -params.yml setup. Though can wait a bit.

**Comment by kyleam** [comment]
I think the plan is now for this to happen in https://github.com/metrumresearchgroup/pmparams

(@seth127 Please reopen if I'm mistaken.)

**Comment by seth127** [comment]
> I think the plan is now for this to happen in https://github.com/metrumresearchgroup/pmparams

Yes, that's right
