### ISSUE TITLE
bump minimum bbr version before release

### ISSUE THREAD

**Issue by kyleam** [metrumresearchgroup/bbr.bayes#124]
The upcoming will have various updates to make the `_log()` functions compatible with nmbayes models, and it's likely to get more as we handle other functions.

* #40
* #36
* #123

This issue is to track making the bbr version constraint update, if any, before the release.   Before deciding, it probably makes sense to let all the bbr-side changes settle (for gh-40 and gh-36).

**Comment by kyleam** [comment]
If the bbr constraint isn't bumped, we should add skips to the `_log()` tests (and perhaps other) when running with an older bbr.

**Comment by seth127** [comment]
We discussed this offline, but I think bumping the bbr version constraint to the next version (likely `1.9.0`) when those changes you mention are released sounds like the right idea.
