### ISSUE TITLE
install_torsten tests: 403 failure

### ISSUE THREAD

**Issue by kyleam** [metrumresearchgroup/bbr.bayes#125]
We recently had a string of builds fail with

```
══ Warnings ════════════════════════════════════════════════════════════════════
── Warning ('test-install-torsten.R:120:5'): install_torsten() works with version and release_url ──
cannot open URL 'https://api.github.com/repos/metrumresearchgroup/Torsten/releases/latest': HTTP status was '403 Forbidden'
Backtrace:
    ▆
 1. ├─bbr.bayes (local) url_to_version(get_torsten_download_url(version = NULL, release_url = NULL)) at test-install-torsten.R:128:3
 2. │ └─base::regexec("([0-9.]+)\\.tar\\.gz$", url) at test-install-torsten.R:120:5
 3. │   └─base::is.factor(text)
 4. └─bbr.bayes:::get_torsten_download_url(version = NULL, release_url = NULL)
 5.   └─bbr.bayes:::latest_torsten_release()
 6.     └─utils::download.file(...)

══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-install-torsten.R:120:5'): install_torsten() works with version and release_url ──
Error in `utils::download.file(url = download_url, destfile = dest_file, 
    quiet = TRUE)`: cannot open URL 'https://api.github.com/repos/metrumresearchgroup/Torsten/releases/latest'
Backtrace:
    ▆
 1. ├─bbr.bayes (local) url_to_version(get_torsten_download_url(version = NULL, release_url = NULL)) at test-install-torsten.R:128:3
 2. │ └─base::regexec("([0-9.]+)\\.tar\\.gz$", url) at test-install-torsten.R:120:5
 3. │   └─base::is.factor(text)
 4. └─bbr.bayes:::get_torsten_download_url(version = NULL, release_url = NULL)
 5.   └─bbr.bayes:::latest_torsten_release()
 6.     └─utils::download.file(...)

[ FAIL 1 | WARN 1 | SKIP 1 | PASS 555 ]
Error: Test failures
Execution halted
```

The URL is live on my end, and I suspect this is just related to rate limiting.  We call `skip_if_over_rate_limit()` in the tests, but I guess that's not sufficient.  (I'm pretty sure that helper is still functional because I see it trigger skips on the bbr side every so often.)

So it might be worth investigating how we could tweak things to avoid this triggering occasional CI failures.  But given the long run-time of the `install_torsten` tests, I lean toward disabling on the CI altogether [*], in which case it's probably not worth looking into.

* <https://github-drone.metrumrg.com/metrumresearchgroup/bbr.bayes/444/1/4>
* <https://github-drone.metrumrg.com/metrumresearchgroup/bbr.bayes/444/2/4>
* <https://github-drone.metrumrg.com/metrumresearchgroup/bbr.bayes/445/1/4>

[*] ... perhaps with a cron job to run them occasionally, one we move to GitHub Actions

**Comment by seth127** [comment]
I just want to confirm that a) this failure appears to be transient and b) we're not considering it a blocker for any releases or anything. Is that right @kyleam ?

**Comment by kyleam** [comment]
@seth127 Correct.  It went away on restart (as expected), and I don't consider it a blocker for release.
