### ISSUE TITLE
audit bbr functions that need tailored nmbayes implementation

### ISSUE THREAD

**Issue by kyleam** [metrumresearchgroup/bbr.bayes#36]
The nmbayes model is largely piggybacking off of the S3 methods for the regular nonmem mode.  Based on the tests added in gh-30, that works okay in most cases.

Known issues:

  * `config_log`, `run_log`, and `summary_log` get tripped up by the sampling submodels (and the fix that likely involves tweaking bbr's `find_models()`). (gh-40)

  * `model_summary` is just a stub implementation at the moment (see gh-27)

However, we should do a wider scan for lurking issues.  For example, `tail_lst` would show the `METHOD=CHAIN` output, not the main output of interest.

**Comment by kyleam** [comment]
I've done a first pass through all of bbr's NAMESPACE and marked whether each function may need work.  These assessments aren't meant to be final, but hopefully they provide a good starting point.  Items with `+` by them have a note under the table.


|                             | needs work?   | blocker? |
|--------------------------- |------------- |-------- |
| **methods**                 |               |          |
| `as_summary_list`           | n? +          |          |
| `build_path_from_model`     | n? +          |          |
| `check_ext`                 | n +           |          |
| `check_grd`                 | **y** +       | y        |
| `check_output_dir`          | **y** +       | y        |
| `check_up_to_date`          | n             |          |
| `config_log_make_entry`     | n +           |          |
| `copy_model_from`           | n             |          |
| `cov_cor`                   | **y**         | y + ?    |
| `create_model_hook`         | n             |          |
| `get_based_on`              | n             |          |
| `get_config_path`           | n             |          |
| `get_data_path`             | n             |          |
| `get_model_ancestry`        | n             |          |
| `get_model_id`              | n             |          |
| `get_model_path`            | n             |          |
| `get_output_dir`            | n             |          |
| `get_yaml_path`             | n             |          |
| `model_diff`                | n             |          |
| `model_summaries`           | **y** (gh-27) | y +      |
| `model_summary`             | **y** (gh-27) | n        |
| `nm_file`                   | **y**? +      | y + ?    |
| `param_estimates`           | **y**         | n        |
| `param_labels`              | n             |          |
| `print`                     | n +           |          |
| `print_model_files`         | n             |          |
| `submit_model`              | n             |          |
| `submit_models`             | **y** (gh-42) | n        |
| `tags_diff`                 | n             |          |
| `tail_lst`                  | **y** +       | y        |
| `tail_output`               | **y** +       | y        |
| `wait_for_nonmem`           | n +           |          |
|                             |               |          |
| **regular functions**       |               |          |
| `add_based_on`              | n             |          |
| `add_bbi_args`              | n             |          |
| `add_config`                | **y** (gh-40) | y        |
| `add_description`           | n             |          |
| `add_notes`                 | n             |          |
| `add_star`                  | n             |          |
| `add_summary`               | **y** (gh-40) | y        |
| `add_tags`                  | n             |          |
| `add_tags_diff`             | n? +          |          |
| `apply_indices`             | n             |          |
| `bbi_current_release`       | n             |          |
| `bbi_help`                  | n             |          |
| `bbi_init`                  | n             |          |
| `bbi_version`               | n             |          |
| `block`                     | n             |          |
| `check_cor_threshold`       | n             |          |
| `check_file`                | n             |          |
| `check_nonmem_finished`     | **y** +       | y        |
| `check_nonmem_table_output` | n             |          |
| `check_run_times`           | **y** +       | y        |
| `check_status_code`         | n             |          |
| `check_yaml_in_sync`        | n             |          |
| `collapse_to_string`        | n             |          |
| `config_log`                | **y** (gh-40) | y        |
| `ctl_ext`                   | n             |          |
| `delete_models`             | n             |          |
| `format_cmd_args`           | n             |          |
| `get_omega`                 | **y** +       |          |
| `get_sigma`                 | **y** +       |          |
| `get_theta`                 | **y** +       |          |
| `mod_ext`                   | n             |          |
| `modify_model_field`        | n             |          |
| `new_ext`                   | n             |          |
| `new_model`                 | n             |          |
| `nm_data`                   | n             |          |
| `nm_grd`                    | **y**? +      | y? +     |
| `nm_join`                   | **y**? +      | n        |
| `nm_par_tab`                | **y**? +      | y? +     |
| `nm_tab`                    | **y**? +      | y? +     |
| `nm_table_files`            | **y**? +      | y? +     |
| `nm_tables`                 | **y**? +      | y? +     |
| `open_model_file`           | n             |          |
| `param_estimates_batch`     | **y**?        | n        |
| `param_estimates_compare`   | n             |          |
| `plot_ext`                  | n +           |          |
| `plot_grd`                  | n +           |          |
| `plot_nonmem_table_df`      | n +           |          |
| `print_bbi_args`            | n             |          |
| `read_bbi_path`             | n             |          |
| `read_model`                | n             |          |
| `reconcile_yaml`            | n             |          |
| `remove_based_on`           | n             |          |
| `remove_notes`              | n             |          |
| `remove_star`               | n             |          |
| `remove_tags`               | n             |          |
| `replace_all_based_on`      | n             |          |
| `replace_all_bbi_args`      | n             |          |
| `replace_all_notes`         | n             |          |
| `replace_all_tags`          | n             |          |
| `replace_description`       | n             |          |
| `replace_model_field`       | n             |          |
| `replace_note`              | n             |          |
| `replace_tag`               | n             |          |
| `run_log`                   | **y** (gh-40) | y        |
| `summary_log`               | **y** (gh-40) | y        |
| `suppressSpecificWarning`   | n             |          |
| `test_threads`              | n +           |          |
| `update_model_id`           | n             |          |
| `use_bbi`                   | n             |          |
| `yaml_ext`                  | n             |          |

Notes for `+` items:

-   `add_tags_diff`: should be ok after `run_log` fix

-   `as_summary_list`: should be ok after `summary_log` fix

-   `build_path_from_model`: this works as intended, though it's not particularly useful given that all the interesting stuff is in submodel subdirectories. Related to d3e400c9 and metrumresearchgroup/bbr#618.

-   `check_ext`, `plot_ext`, `plot_grd`, `plot_nonmem_table_df`: deprecated in bbr 1.5.0 so probably fine to leave unsupported

-   `check_grd`: expects grd files to be in top-level output directory

-   `check_nonmem_finished`, `tail_lst`: expects `.lst` to be in top-level output directory

-   `check_output_dir`: expects output files to be in top-level output directory

-   `check_run_times`: requires model summary and `wait_for_nonmem`

-   `config_log_make_entry`: this is an "internal" method exposed for making `config_log` work with Stan models. May be involved in solution for gh-40.

-   `cov_cor` runs `bbi nonmem covcor` on the top-level output directory

-   `get_theta`, `get_omega`, `get_sigma`, `param_estimates`: bbr relies on a summary object, so blocked by gh-27. Not labeling as blocker itself given that the error is inaccessible without a summary object.

-   `model_summaries`: in terms of being a blocker, this should at least abort with an informative error.

-   `nm_file`, `nm_grd`, `nm_par_tab`, `nm_table_files`, `nm_tables`, `nm_tab`: error saying that files were not found in top-level output directory. I'm not sure how much we want to support this and there is `chain_paths` for getting files from submodels, but it seems like it should at least give a better error.

-   `nm_join`: there is of course `nm_join_bayes` for nmbayes models, but should `nm_join` give a better error on nmbayes models?

-   `param_estimates_batch`: relies on `bbi nonmem params` to discover models within directory, and bbi of course doesn't understand submodels.

-   `print`: works fine, but at some point perhaps worth considering adding other info (e.g., the number of chains)

-   `tail_output`: expects OUTPUT file in top-level output directory

-   `test_threads`: this relies on `submit_models`, so it's blocked by gh-42.

-   `wait_for_nonmem`: should work once `check_nonmem_finished` is fixed

**Comment by seth127** [comment]
Thanks for this @kyleam ; very helpful as a starting point for addressing these.

Looking over the table and notes, I don't see anything particularly surprising to me (which is good). I'm looking forward to breaking these out into dedicated issues, and prioritizing as needed, in the new year.

**Comment by kyleam** [comment]
[ building from table above, capturing plan discussed with @seth127 on a call]

## short overview planned changes

-   add tailored nmbayes method, error: `cov_cor`, `nm_file`

-   add tailored nmbayes method, functional: `tail_lst`, `tail_output`

-   add kludge with tailored handling for nmbayes model in `bbr::nm_join`.

-   convert `check_nonmem_finished` function to a method and add tailored nmbayes method

-   adjust `check_run_times` to use underlying method and add one for Stan and nmbayes (perhaps not for this bbr.bayes release)


## more details


### methods

-   `check_grd` (leave be)
    
    Don't bother with because `check_grd` is deprecated in favor of `nm_grd`. Error about a `.grd` file not existing in top-level directory is good enough.

-   `check_output_dir` (leave be)
    
    The current behavior may be okay: calls `fs::dir_ls` in output directory, listing submodels and model files. If you want more detail, can pass `recurse = TRUE` through to `dir_ls`.

-   `cov_cor` (new method, error)
    
    `bbi nonmem covcor` call on top-level model will fail with message like "no file present /path/to/mod/mod.cov".
    
    The submodels each have a `.cov` file. Is there something reasonable we could return there? `bbi nonmem covcor` call for each submodel, returning a list? (It's unfortunate that the return value type would be different than that of plain NONMEM models.)
    
    Initial plan is for is to add a tailored method that gives a more appropriate error.

-   `model_summaries` (leave be)
    
    With [bbr#645](https://github.com/metrumresearchgroup/bbr/pull/645), works as fine as can be expected until we work through what `model_summary` should show ([bbr.bayes#27](https://github.com/metrumresearchgroup/bbr.bayes/issues/27)).

-   `model_summary` (leave be for now)
    
    [bbr.bayes#27](https://github.com/metrumresearchgroup/bbr.bayes/issues/27)

-   `nm_file` (new method, error)
    
    Abort and point to `chain_paths`.

-   `param_estimates` (leave be for now)
    
    Relies on having a `bbi_nonmem_summary` object, which you can't currently get for an nmbayes model. It seems likely that what results from [bbr.bayes#27](https://github.com/metrumresearchgroup/bbr.bayes/issues/27) may not be a `bbi_nonmem_summary` object (given how tied that is to `bbi`), but either way there's nothing to do here until that's sorted out.
    
    (Similar functionality for both Stan and nmbayes can be accessed through the draws object.)

-   `submit_models` (leave be for now)
    
    Right now, both Stan and nmbayes models error with a clear "Unsupported model type: &#x2026;".
    
    This would need to be implemented to support `test_threads`.
    
    Mostly relevant for NONMEM context of grouping calls with same bbi args and bootstrapping.
    
    [bbr.bayes#42](https://github.com/metrumresearchgroup/bbr.bayes/issues/42)

-   `tail_lst` (new method)
    
    Should probably return tail of `lst` for each chain directory.

-   `tail_output` (new method)
    
    Should probably return tail of `OUTPUT` each chain directory.


### regular functions

-   `check_nonmem_finished` (convert to method)
    
    Would always return `FALSE` because top-level file doesn't exist.
    
    Plan is to make `check_nonmem_finished` a method and then nmbayes can have method that loops over chain paths.

-   `check_run_times` (adjust eventually, probably leave be for now)
    
    Eventual plan is to move the "run time for model" [operation](https://github.com/metrumresearchgroup/bbr/blob/eadc261a35e5f708c4c0f23b9aa470a066c7c98f/R/test-threads.R#L162-L203) to a method.
    
    Main design decision at the user-facing interface level will be handling of the `.return_times` argument, which is very coupled to the `bbi_nonmem_summary` object at the moment.
    
    This may be delayed until after the upcoming `bbr.bayes` release, leaving `check_run_times` to error (at `model_summary` call) for Stan and nmbayes models.

-   `config_log`, `add_config` (done)
    
    [bbr#643](https://github.com/metrumresearchgroup/bbr/pull/643) [bbr#644](https://github.com/metrumresearchgroup/bbr/pull/644) [bbr.bayes#123](https://github.com/metrumresearchgroup/bbr.bayes/pull/123)

-   `get_theta`, `get_omega`, `get_sigma` (leave be for now)
    
    Relies on `param_estimates` and thus on having a `bbi_nonmem_summary` object, so same comments there apply.

-   `nm_grd`, `nm_par_tab`, `nm_tab`, `nm_table_files`, `nm_tables` (leave be)
    
    Fails saying respective file doesn't exist (in top-level model).
    
    Should be covered by tailored `nm_file` error.

-   `nm_join` (adjust bbr to give tailored error)
    
    Fails saying table file doesn't exist (in top-level model). This is on bbr end, so of course there's no pointer to `nm_join_bayes`.
    
    Plan is to add kludge for handling on bbr side.

-   `param_estimates_batch` (leave be)
    
    Passing a directory with NONMEM Bayes models to `bbi nonmem params --dir` would fail with a message like "open dir/mod/mod.ext: no such file or directory"".
    
    Fine as is.

-   `run_log` (done)
    
    [bbr#643](https://github.com/metrumresearchgroup/bbr/pull/643)

-   `summary_log`, `add_summary` (leave be for now)
    
    [bbr#643](https://github.com/metrumresearchgroup/bbr/pull/643) [bbr#645](https://github.com/metrumresearchgroup/bbr/pull/645)
    
    Working in terms of not failing, but there's the larger related question of what the model summary for NONMEM Bayes should be ([bbr.bayes#27](https://github.com/metrumresearchgroup/bbr.bayes/issues/27)). And also the question of whether it may make sense to add variants like `stan_summary_log` and `stan_add_summary` (although, then again, we're undecided about whether those should eventually be incorporated into `summary_log` and `add_summary`).

**Comment by kyleam** [comment]
Follow-up issues posted at

 * https://github.com/metrumresearchgroup/bbr.bayes/issues/129
 * https://github.com/metrumresearchgroup/bbr.bayes/issues/130

---

This issue can be closed once these in-flight PRs land:

- [ ] https://github.com/metrumresearchgroup/bbr.bayes/pull/126
- [ ] https://github.com/metrumresearchgroup/bbr/pull/662
- [ ] https://github.com/metrumresearchgroup/bbr/pull/661
- [ ] https://github.com/metrumresearchgroup/bbr.bayes/pull/127 (depends on previous bbr PR)
- [ ] https://github.com/metrumresearchgroup/bbr/pull/663
- [ ] https://github.com/metrumresearchgroup/bbr.bayes/pull/128 (depends on previous bbr PR)
