### ISSUE TITLE
stan: input data change with jsonlite 1.8.5

### ISSUE THREAD

**Issue by kyleam** [metrumresearchgroup/bbr.bayes#88]
The jsonlite 1.8.4 to 1.8.5 update (yet to hit MPN) triggers `check_update_to_date` test failures:

```
$ Rscript -e 'devtools::test(filter = "check-up-to")'
ℹ Testing bbr.bayes
✔ | F W S  OK | Context
✖ | 3      16 | check-up-to-date [0.7s]
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Failure (test-check-up-to-date.R:33:5): stan: check_up_to_date() happy path
check_up_to_date(mod) not equal to `ALL_GOOD`.
1 element mismatch

Failure (test-check-up-to-date.R:44:5): stan: check_up_to_date() with mismatched model
`res` not equal to `MODEL_BAD`.
1 element mismatch

Failure (test-check-up-to-date.R:44:5): stan: check_up_to_date() with mismatched model
`res` not equal to `MODEL_BAD`.
1 element mismatch
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

══ Results ════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 0.7 s

[ FAIL 3 | WARN 0 | SKIP 0 | PASS 16 ]
```

With a quick glance, looks like the data isn't matching up.  That's presumably because the `jsonlite::write_json` call (triggered by `build_data`) is producing slightly different output when formatting identical content.

**Comment by kyleam** [comment]
> presumably because the `jsonlite::write_json` call (triggered by `build_data`) is producing slightly different output when formatting identical content.

Hmm, when I wrote that, I was guessing something like spacing was changing.  It's actually a difference in the number of digits used when writing to json: b5398e2 (Changing 15 significant digits to 17, 2023-02-12).  See jsonlite's PR 413 and issues 350 and 412 for more background.

We'll need to come up with a plan for how to handle this.

**Comment by kyleam** [comment]
Overview of the issue:

 * `build_data()` calls `cmdstanr::write_stan_json()` to generate the JSON data file.

 * `cmdstanr::write_stan_json()` [calls](https://github.com/stan-dev/cmdstanr/blob/22b391e68c9577bafcc0ae0721d8dc32a14e341b/R/data.R#L101-L109) `jsonlite::write_json()` with `digits = NA`, which means print numbers with "max precision".

 * What "max precision" means changed with jsonlite v1.8.5.  Before v1.8.5 (specifically [b5398e2](https://github.com/jeroen/jsonlite/commit/b5398e2b9264d99b694d430d4f76e7879b146fd5)), 15 significant digits were used.  As of v1.8.5, 17 significant digits are used to ensure that the binary value is preserved when converting to base 10 and then back again.

   <details>
   <summary>round-trip demo</summary>
   
   ``` r
   packageVersion("jsonlite")
   #> [1] '1.8.4'
   
   x <- 1/3
   y <- jsonlite::fromJSON(jsonlite::toJSON(x, digits = NA))
   
   identical(x, y)
   #> [1] FALSE
   sprintf("%0.17g", x)
   #> [1] "0.33333333333333331"
   sprintf("%0.17g", y)
   #> [1] "0.33333333333333298"
   ```
   
   ``` r
   packageVersion("jsonlite")
   #> [1] '1.8.5'
   
   x <- 1/3
   y <- jsonlite::fromJSON(jsonlite::toJSON(x, digits = NA))
   
   identical(x, y)
   #> [1] TRUE
   sprintf("%0.17g", x)
   #> [1] "0.33333333333333331"
   sprintf("%0.17g", y)
   #> [1] "0.33333333333333331"
   ```
   
   </details>

 * That change will lead to `build_data/write_stan_json` producing different input data files in nearly all cases.


---

As a result of this change, cmdstan is fed different data depending on whether the user is running jsonlite >= 1.8.5, and we can't expect cmdstan to produce identical sampling results.  (I've confirmed with the fxa test model generates different results for jsonlite 1.8.4 and jsonlite 1.8.5.)

Here's my proposal for how to proceed:

 * update the Stan `check_up_to_date` steps for the jsonlite >= 1.8.5 expectations, adding a skip for environments where jsonlite is below 1.8.5

 * once jsonlite 1.8.5 hits MPN, make the that the minimum required version and drop the skip

The goal of the second item is to try to prevent users for hitting into this, but that of course doesn't prevent triggering the issue with models that have already been generated.  However, given the early stage of bbr.bayes, it doesn't seem likely that there are many non-toy/dev models out there yet, so hopefully this won't be the source of too much headache or confusion.  (Also, all Metrum projects are isolating/pinning their packages, in which case this issue won't be encountered unless the project decides to explicitly update.)

**Comment by kyleam** [comment]
Here's a example with just cmdstanr and a simple model:

<details>
<summary>jsonlite 1.8.4</summary>

``` r
packageVersion("jsonlite")
#> [1] '1.8.4'

display_values <- function(xs) {
  for (x in xs) {
    message(sprintf("%.17g", x))
  }
}

scode <- "
data {
  int<lower=0> N;
  vector[N] y;
}

parameters {
  real<lower=0> sigma;
}

model {
  y ~ normal(0, sigma);
}
"

set.seed(393)

n <- 5L
data <- list(
  N = n,
  y = rnorm(n)
)

display_values(data$y)
#> -0.61423287504092405
#> 0.0024292715483109897
#> 0.55170124785166563
#> -0.8159527728525322
#> -0.70882754738259945

mod <- cmdstanr::cmdstan_model(cmdstanr::write_stan_file(scode))
withr::with_output_sink(
  "/dev/null",
  fit <- mod$sample(data = data, seed = 281, chains = 2)
)

fit$draws("lp__")
#> # A draws_array: 1000 iterations, 2 chains, and 1 variables
#> , , variable = lp__
#>
#>          chain
#> iteration    1     2
#>         1 -2.1 -0.47
#>         2 -1.7 -0.47
#>         3 -1.1 -1.60
#>         4 -2.2 -1.15
#>         5 -2.4 -0.46
#>
#> # ... with 995 more iterations

unname(tools::md5sum(fit$data_file()))
#> [1] "2a1e369df02d701a4bd0dbb9685c661a"
data1 <- jsonlite::read_json(fit$data_file())
display_values(data1$y)
#> -0.61423287504092405
#> 0.0024292715483109901
#> 0.55170124785166597
#> -0.81595277285253198
#> -0.70882754738259901

data$y == data1$y
#> [1]  TRUE FALSE FALSE FALSE FALSE
```

</details>

<details>
<summary>jsonlite 1.8.5</summary>


``` r
packageVersion("jsonlite")
#> [1] '1.8.5'

display_values <- function(xs) {
  for (x in xs) {
    message(sprintf("%.17g", x))
  }
}

scode <- "
data {
  int<lower=0> N;
  vector[N] y;
}

parameters {
  real<lower=0> sigma;
}

model {
  y ~ normal(0, sigma);
}
"

set.seed(393)

n <- 5L
data <- list(
  N = n,
  y = rnorm(n)
)

display_values(data$y)
#> -0.61423287504092405
#> 0.0024292715483109897
#> 0.55170124785166563
#> -0.8159527728525322
#> -0.70882754738259945

mod <- cmdstanr::cmdstan_model(cmdstanr::write_stan_file(scode))
withr::with_output_sink(
  "/dev/null",
  fit <- mod$sample(data = data, seed = 281, chains = 2)
)

fit$draws("lp__")
#> # A draws_array: 1000 iterations, 2 chains, and 1 variables
#> , , variable = lp__
#>
#>          chain
#> iteration    1     2
#>         1 -2.0 -4.29
#>         2 -2.7 -1.57
#>         3 -3.6 -1.23
#>         4 -3.8 -0.85
#>         5 -3.8 -1.60
#>
#> # ... with 995 more iterations

unname(tools::md5sum(fit$data_file()))
#> [1] "e3cbb2662635931c4614f600b2b9fd36"
data1 <- jsonlite::read_json(fit$data_file())
display_values(data1$y)
#> -0.61423287504092405
#> 0.0024292715483109897
#> 0.55170124785166563
#> -0.8159527728525322
#> -0.70882754738259945

data$y == data1$y
#> [1] TRUE TRUE TRUE TRUE TRUE
```

</details>

**Comment by frenchjl** [comment]
@kyleam @seth127 
Thanks for the thorough exploration and clear description of the issue.

I'm not aware of any non-toy/dev use of  bbr.bayes yet.  That, coupled with the package management, leads me to think there is a low probability of this issue causing any meaningful impact on client project work.  However, just to be sure, I'll check with the stats group about bbr.bayes usage.

**Comment by kyleam** [comment]
@seth127 @frenchjl Thanks for the input.

> I like your proposal

All right, I'll move ahead with the first part.

---

If there do turn out to be any active Metrum projects, in my view it comes down to making them aware of the potential reproducibility issue and deciding how to handle it on the project end.  On the bbr.bayes end, I'm not seeing any real path forward that maintain stable results across the jsonlite update.

**Comment by kyleam** [comment]
@seth127 @frenchjl Actually, thinking about this a bit more, I don't think the question of whether projects are using `bbr.bayes` is the relevant one.  This matters for the reproducibility of any project using cmdstanr _if_ they're feeding in an R object as `data` (see [example above](https://github.com/metrumresearchgroup/bbr.bayes/issues/88#issuecomment-1581625760)) or generating data with `jsonlite` and giving the path to `cmdstan{,r}`.  `bbr.bayes` being the driver isn't important, except that its `check_up_to_date` may make the issue more obvious by flagging the change.

**Comment by kyleam** [comment]
jsonlite 1.8.7 is back to using 15 instead of 17 digits when `digits = NA` ([120cca8d](https://github.com/jeroen/jsonlite/commit/120cca8df83f6f6e6ce26610b113c15e881a95de)).  That was actually prompted by cmdstanr devs reporting the change due to it causing failures in their tests.

So, assuming that stands, I think we should

 * revert relevant changes form gh-89
 * close gh-91 without merge.  As far as I know, R doesn't allow specifying version constraints in a way that "avoids" a version, so there's really nothing to do to avoid this potential source of discrepancies in input data/results.

(It's unfortunate that data written by jsonlite before 1.8.5 and after 1.8.7 won't reliably round-trip for float64.  I expect it also won't match CmdStanPy's `write_stan_json`, given that should follow Python 3's repr's approach of truncating to the shortest string that's not ambiguous.)

**Comment by kyleam** [comment]
> Am I reading it right that this only happens when `digits = NA`? 

With jsonlite 1.8.7, yes.  You could pass in 17 for `digits`.  With jsonlite > 1.8.5, the value you pass in will be capped at 15.

> Can we skirt around this by _not_ calling it this way?

We don't call it, cmdstanr does (overview of call chain at https://github.com/metrumresearchgroup/bbr.bayes/issues/88#issuecomment-1581469350).

We could write the data ourselves, but [cmdstanr::write_stan_json](https://github.com/stan-dev/cmdstanr/blob/dbf41cd389dc8e2902676bf205d34e40a0f51a05/R/data.R#L59-L110) has other involved logic that I don't think we want to take on.

**Comment by seth127** [comment]
Well, it seems like we may be backed into a corner then. Do you see any other path forward, or do we just have to swallow that `jsonlite 1.8.6` writes differently than other versions and hope it doesn't bite someone?

**Comment by kyleam** [comment]
> Do you see any other path forward, or do we just have to swallow that `jsonlite 1.8.6` writes differently than other versions and hope it doesn't bite someone?

The main thing I can think of is marking a set of "bad" versions with constraints, but lI don't think R supports that sort of version constraint.  I'm open to other ideas, but I don't see anything for us to do (aside from restore the 15-digit expectations: gh-93).

**Comment by seth127** [comment]
Ok, that makes sense to me. Thanks for keeping up with this. I approved #93
